### ISSUE TITLE
Refresh Eureka Client OAuth Token

### ISSUE THREAD

**Issue by cwoodworth** [jquatier/eureka-js-client#103]
Is it possible to refresh the custom client middleware on a reoccurring basis?  My service registry is running behind OAuth 2.0 and requires a token refresh every 30 seconds.  I don't see a way in the README to hook into the running client and modify the auth once it has been created.  Any help you can provide is greatly appreciated.

```
const client = new Eureka({
      // application instance information
      requestMiddleware: function(requestOpts, done) {
            requestOpts.auth = {
                  'bearer': accessToken.token.access_token  //THIS NEEDS TO BE REFRESHED
            };
      done(requestOpts);
},
```

**Comment by jquatier** [comment]
Hey @cwoodworth, Thanks for the question. We added the `requestMiddleware` feature recently, and made it support asynchronous functions for this exact purpose (oAuth). The goal of the request middleware functionality was to allow users to execute any code they required before the request executes. The middleware function is called on EVERY request, so you can execute whatever actions are needed for your use case. This allows the client to remain agnostic to things like oAuth or other kinds of authentication, and allows consumers full flexibility.

For your case, I would just determine if the token needs to be refreshed and refresh it in that middleware function. If a refresh is not necessary, return the current token in the headers. To add to your example:

```javascript
const client = new Eureka({
  // application instance information
  requestMiddleware: function(requestOpts, done) {
    const requestToken = 
    if(needsRefresh(accessToken.token)) {
      // make necessary token refresh calls here, then add to the requestOpts and call done();
      request(my_refresh_url, function (error, response, body) {
        if (!error && response.statusCode == 200) {
          requestOpts.auth = { 'bearer': body.token.access_token };
          accessToken = body.token; // save the new token for later usage
          done(requestOpts);
        }
      });
    } else {
      // token doesn't need to be refreshed, just use the current token (accessToken)
      requestOpts.auth = { 'bearer': accessToken.token.access_token };
      done(requestOpts);
    }
},
```

Hope this helps!

**Comment by cwoodworth** [comment]
Awesome, thanks! This is exactly what I was hoping for.  I'll give it a shot tomorrow.
