### ISSUE TITLE
Need help getting started when using domains vs plain IP addresses

### ISSUE THREAD

**Issue by fabiogomezdiaz** [jquatier/eureka-js-client#106]
Let's say I have the following 
- **Eureka** deployed at:
  - https://netflix-eureka-fabio.mybluemix.net/
  - Note I don't need to specify the port as networking takes care of it
- **Node.js App** deployed at:
  - https://node-app-fabio.mybluemix.net/
  - Same port scenario as above

Bluemix (from IBM) is a platform as a service offering, much like Heroku.

Is this the correct way to set things up? If so, I am getting a 404 and can't figure out what do do.
```javascript
const client = new Eureka({
	// application instance information
	instance: {
		app: 'some-microservice',
		hostName: 'node-app-fabio.mybluemix.net',
		ipAddr: 'node-app-fabio.mybluemix.net',
		port: true,
		vipAddress: 'some.app.com',
		dataCenterInfo: {
			name: 'MyOwn',
		},
	},
	eureka: {
		// eureka server host / port
		host: 'netflix-eureka-fabio.mybluemix.net',
		port: true
	},
});
```

It must be something simple I am missing on. Also, what is the vipAddress? Don't remember seeing this when using eureka java client

**Comment by jquatier** [comment]
@fabiogomezdiaz I definitely would not set port to `true` as that will probably cause adverse effects. If your server is simply available without a port in your browser, that means it's on port `80` or `443` if its https so I would use that in your config. As for the 404 errors, those usually happen when it can't find the Eureka REST service. You may need to locate what path the service is located on per the information here: https://github.com/jquatier/eureka-js-client#404-not-found-errors-from-eureka-server
