### ISSUE TITLE
Stop doing everything in constructor?

### ISSUE THREAD

**Issue by kesne** [jquatier/eureka-js-client#11]
Would it make sense to have the constructor just prepare the client instance, and then expose the register/fetchRegistry methods (or a `start` method that does both)?

The benefit of doing that is it makes testing stuff a lot easier. Otherwise we kind of have to stub those calls every time we try to test the constructor, which is less than ideal.

**Comment by jquatier** [comment]
:+1: I'm good with that. I do think heartbeats should start after register though.

**Comment by kesne** [comment]
Or should heartbeats happen after registration has been completed?

**Comment by kesne** [comment]
That makes sense to me. I'll implement it in the next PR.

**Comment by daveedgarcia** [comment]
Up vote on this one. I held off on testing because of this reason.

**Comment by daveedgarcia** [comment]
Is someone taking this or should I take it?

**Comment by kesne** [comment]
Fixed by #13.
