### ISSUE TITLE
The Eureka is broken when I register a service

### ISSUE THREAD

**Issue by ikercrg** [jquatier/eureka-js-client#113]
I have a Eureka with other services registered on it which works correctly.

The problem is that I am trying to register a javascript application with eureka-js-client, and apparently the registration goes well but, after it, I cannot access anymore the Eureka because I get nullpointerException and the Eureka is down.

I am working with AWS and I passed the Eureka host and Eureka port via environment variables.

**The configuration I set**

```
var discoveryServiceHostName = process.env.EUREKA_HOST || 'localhost';
var discoveryServicePort = process.env.EUREKA_PORT || '8761';

var Eureka = require('eureka-js-client').Eureka;

var client = new Eureka({
  instance : {
    app : 'feedbackapi',
    port : {
      '$' : 8081,
      '@enabled' : true
    },
    vipAddress : 'feedbackservice',
    dataCenterInfo : {
      '@class': 'com.netflix.appinfo.AmazonInfo',
      name : 'Amazon'
    }
  },
  eureka : {
    host : discoveryServiceHostName,
    port : discoveryServicePort,
    useLocalMetadata : true,
    preferIpAddress : true,
    servicePath : '/eureka/apps/'
  }
});

client.logger.level('debug');
client.start();
```

**The message I get**

> server listening on port number 8081
> Found Instance AWS Metadata { 'ami-id': 'ami-ec2be583',
>  some-data}
> registered with eureka:  feedbackapi/i-0d8e01ac4d15179b8
> retrieved registry successfully
> eureka heartbeat success

**After this the Eureka is not working anymore, and this the exception I get**

> java.lang.NullPointerException: null
>         at org.springframework.cloud.netflix.eureka.server.EurekaController.populateApps(EurekaController.java:237) ~[spring-cloud-netflix-eureka-server-1.1.0.RELEASE.jar!/:1.1.0.RELEASE]

**In EurekaController.java:237 this is what it is**

instance.put("url", url);
Extracted from: https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-eureka-server/src/main/java/org/springframework/cloud/netflix/eureka/server/EurekaController.java

**Comment by ikercrg** [comment]
It seems like it was the following:

This was missing in the configuration:
statusPageUrl: 'http://__HOST__:8081',
healthCheckUrl: 'http://__HOST__:8081',
homePageUrl: 'http://__HOST__:8081',

Strange, because the registration was correct

**Comment by jquatier** [comment]
Yeah, I think this has come up before. For whatever reason, in the Spring Cloud version of Eureka those URLs seem to be required. I'll make a quick update to the README and reference this issue for posterity. Glad you got it working!
