### ISSUE TITLE
spring cloud robbin cannot find service

### ISSUE THREAD

**Issue by fatshaw** [jquatier/eureka-js-client#121]
I register client with code below. And in the spring eureka website i can see the service i registered. but i cannot get service info with robbin.

const Eureka = require('eureka-js-client').Eureka;

// example configuration

const client = new Eureka({
  // application instance information
  instance: {
    app: 'jqservice',
    hostName: '192.168.76.82',
    ipAddr: '192.168.76.82',
    port: {
      '$': 3000,
      '@enabled': true,
    },
    vipAddress: 'jq.test.something.com',
    statusPageUrl: 'http://192.168.76.82:3000/info',
    healthCheckUrl: 'http://192.168.76.82:3000/health',
    dataCenterInfo: {
      '@class': 'com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo',
      name: 'MyOwn',
    },
  },
  eureka: {
    // eureka server host / port
    host: 'eureka-primary.futures-dev.98.cn',
    port: 80,
    servicePath: '/eureka/apps/',
    preferIpAddress:true
  },
});

client.start();

**Comment by jquatier** [comment]
If the Eureka website shows the service registered, that means this module is working correctly. As for accessing the service, it depends on how you are making the request. It looks like you are setting the `vipAddress` to my example vip still, so you may want to adjust that value to the name of your application. Then, in the code that accesses the service (Ribbon, etc), use the correct vip address to configure the client.
