### ISSUE TITLE
Eureka client heart beat stopped but still showing in Eureka server

### ISSUE THREAD

**Issue by nkravi** [jquatier/eureka-js-client#123]
I have stopped my eureka client. But still the client name shows up on Eureka server.
Here is my code.
Am I missing something here?

const Eureka = require('eureka-js-client').Eureka;
var express = require('express')
var ip = require("ip");

const client = new Eureka({
  // application instance information
  instance: {
    app: 'frontend',
    instanceId : 'feapp',
    hostName: 'localhost',
    ipAddr: ip.address(),
    port: {
      '$': process.env.PORT || 5050,
      '@enabled': true,
    },
    vipAddress: 'jq.test.something.com',
    dataCenterInfo: {
      '@class': 'com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo',
      name: 'MyOwn',
    },
  },
  eureka: {
    // eureka server host / port
    host: 'localhost',
    port: 8761,
    servicePath: '/eureka/apps/',
    fetchRegistry: true,
    heartbeatInterval:3000,
    registerWithEureka:true
    //preferIpAddress:true
  },
});
client.logger.level('debug');
var app = express()
app.use(express.static('dist'))
var PORT = process.env.PORT || 5050
app.listen(PORT, function () {
  client.start();
  console.log('Express server listening on port ' + PORT)
})

**Comment by jquatier** [comment]
The Eureka server doesn't drop the instance out of the registry immediately. It waits until it hasn't seen a heartbeat from that server in several minutes (configurable).

**Comment by nkravi** [comment]
thanks @jquatier . Does this configuration has to be from server side or client side? If it is from the client side what is the parameter i need to set?

**Comment by jquatier** [comment]
It's a setting on the Eureka server that applies to all registrations.

**Comment by nkravi** [comment]
I am little bit confused here. I have other clients which uses spring cloud(Eureka discovery). Eureka server immediately evicts these clients when heart-beat is stopped. But Nodejs client stays there for hours

**Comment by jquatier** [comment]
That's not really possible unless another instance is still sending heartbeats using the same app ID and instance ID. I would take a look at the last updated timestamp in the registry and debug from there. Your Eureka server will only drop records out if it hasn't gotten a heartbeat.
