### ISSUE TITLE
NODE_DEBUG=request does not tell me what is response body

### ISSUE THREAD

**Issue by sachinsharma** [jquatier/eureka-js-client#130]
I am trying to get and instance by appId by using the method. However the log says "Unable to retrieve instances for appId: '<my-app-id>'"

I think I am not passing the app-id properly and want to look what is retrieved from the eureka server when the following endpoint is called: http://my-eureka-server:80/eureka/apps/

Setting NODE_DEBUG=request tells me that the url was called successfully and that the return status was 200. But nowhere can I see the returned response body json.

Is there a way I can see the response body for http requests made by the eureka-js-client package?

**Comment by sachinsharma** [comment]
I mean I can access the url in browser and see response in xml format.
But I assumed whatever is being returned in <app> and <vipAddress> tags will be read by the eureka-js-client package and will be returned in the method calls 

const instances = client.getInstancesByAppId('xxxx-microservices');
const instances = client.getInstancesByVipAddress('xxxx-microservices');

But that is not the case. So I want to see what are the contents of 'this.cache.app[]' in line 312 of https://github.com/jquatier/eureka-js-client/blob/master/src/EurekaClient.js

const instances = this.cache.app[appId.toUpperCase()] || [];

So that I can see the error on my part in calling the above two methods.

**Comment by sachinsharma** [comment]
OK.

The problem was two-fold here.
And none of them belonged here in this forum.

First was related to the process of debugging nodejs apps themselves.
=============
NODE_DEBUG=request is a basic way of debugging but for more details, we need to use the --inspect option while starting the node app and with it comes all the tunneling stuff and chrome://inspect thing.
I became familiar with it and was able to see the response body in chrome inspector.

Second problem was the location of "client.getInstancesByAppId('xxxx-microservices')" method call.
======================
It has to be called within a callback method supplied to client.start(callback).
Not immediately after client.start() call.

These two are javascript novice issues and not related to this package. Thanks for your patience.

**Comment by jquatier** [comment]
Glad you figured it out 👍
