### ISSUE TITLE
Update spring cloud configuration

### ISSUE THREAD

**Issue by famargon** [jquatier/eureka-js-client#133]
Hi,
in [this](https://github.com/spring-cloud/spring-cloud-netflix/issues/2588#issuecomment-366009329) issue we discussed about a problem with zuul and microservices registered in eureka with eureka-js-client. Today I found that the problem was in the eureka-js-client configuration. It will be cool to update the sample configuration to spring cloud.

```
const eureka = new Eureka({
  instance: {
    id: 'node-simple-service',    
    instanceId: 'node-simple-service',
    app: 'node-simple-service',
    hostName: 'localhost',
    ipAddr: '127.0.0.1',
    statusPageUrl: 'http://localhost:8200',
    port: {
      '$': SERVER_PORT,
      '@enabled': 'true',
    },
    vipAddress: 'node-simple-service',
    dataCenterInfo: {
      '@class': 'com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo',
      name: 'MyOwn',
    }
  },
  eureka: {
    host: 'localhost',
    port: 8761,
    servicePath: '/eureka/apps/'
  }
});
```
Thank you!!

**Comment by jquatier** [comment]
We have this in the README already under a [section](https://github.com/jquatier/eureka-js-client#usage-with-spring-cloud) for Spring Cloud. We have to have both types of config because different users are using different versions of Eureka.

**Comment by famargon** [comment]
The instanceId is neccesary to make ribbon work with eureka

**Comment by jquatier** [comment]
It depends on the deployment. Under AWS deploys, the instance ID comes from the AWS metadata. We also allow it to be configured, else it defaults to the hostName. It's not required in all spring cloud deployments, since it depends on the usage.
