### ISSUE TITLE
there should be optional callback/function that is checked in the heartbeat

### ISSUE THREAD

**Issue by maksimlikharev** [jquatier/eureka-js-client#137]
it needs a logic to fail to register based on internal checks, that can be passed to a client.

This is a use case.

1. service starts, registers in the eureka, starts heartbeat
2. during a life of the service, something falls off, healthcheck will report error, if called, but eureka status will be UP

rationale, sync healthchecks with heartbeat, this is pretty much what java driver does.

I can probably do pr if you busy, but I need this asap

**Comment by seanohollaren** [comment]
Shouldn't this logic be in your own service's code wherever you register the heartbeat listener?  

Since your service is the one answering heartbeat requests, you can instead change that logic to be dependent on whatever you want instead of always responding with 200.

**Comment by maksimlikharev** [comment]
Heartbeat registered inside EurekaJS component if I want to register with eureka

And it will be called regardless if my instance is healthy or not, what I want is to be able to provide a feedback to re-registration loop with health.

Java driver has this, always had:

void refreshInstanceInfo() {
   applicationInfoManager.refreshDataCenterInfoIfRequired();
   applicationInfoManager.refreshLeaseInfoIfRequired();

   InstanceStatus status;
   try {
       status = getHealthCheckHandler().getStatus(instanceInfo.getStatus());
   } catch (Exception e) {
       logger.warn("Exception from healthcheckHandler.getStatus, setting status to DOWN", e);
       status = InstanceStatus.DOWN;
   }

   if (null != status) {
       applicationInfoManager.setInstanceStatus(status);
   }
}


What it does, it marks instance down, if healthcheck is failed ( it calls it internally in the renew loop), this is what I want to achieve in js client as well, tap into renew loop and provide update.
Alternatively I have to produce my own scheduler, it will be a different scheduler, might fail differently, and deregister, but since you specifically claim that is js implementation of https://github.com/Netflix/eureka, so important feature of java driver is missing.

Thanks.

**Comment by maksimlikharev** [comment]
service up or down is dynamic , it can be up and after some time it might be down, 
node service runs, usually, under supervisor, so even if I kill the service, it will be restarted, repeating the circle, this is what I observe for node services in our env, java services, btw, behaving much more predictable in similar situation.

**Comment by jquatier** [comment]
Agreed but in the normal pattern clients use load balancing and circuit breaking anyway, since their cache may be out of date. Closing for now, if you want to PR this feature, send it over. Thanks!
