### ISSUE TITLE
no instance

### ISSUE THREAD

**Issue by mfulton26** [jquatier/eureka-js-client#138]
I would like to use `eureka-js-client` in my test code. As such, I do not need (nor want) to register an instance with Eureka. How might I be able to make a read-only Eureka client with `eureka-js-client`? Thanks.

**Comment by mfulton26** [comment]
Never mind, I found `registerWithEureka`.

FYI: I got `TypeError: Missing "instance.app" config value.` when I first tried. It might be good to include in the error message a note/hint that `registerWithEureka` can be used if the user does not want to register an instance.

**Comment by AlessioMTX** [comment]
Could you explain what  you did? I don't find instances too
