### ISSUE TITLE
Request to another apps in Eureka

### ISSUE THREAD

**Issue by andresmafra** [jquatier/eureka-js-client#146]
Hi, thanks for the API, it's is very helpful.

But, I couldn't understand how can I make a request  to another app registered in same Eureka that my app are.

I use the function **getInstancesByAppId** for list my app, and it works as expected.

But, how can I make a request for this another app?

Regards.

**Comment by seanohollaren** [comment]
Once you know the IPs of the service instances, you can just perform requests to them the same way you'd perform any other HTTP requests, like with the `request` module.

**Comment by jquatier** [comment]
Agreed. This module is used for service discovery, the requests can be done with any http library.
