### ISSUE TITLE
Integration Tests using Eureka Docker Image

### ISSUE THREAD

**Issue by daveedgarcia** [jquatier/eureka-js-client#17]
Should we add a script for downloading the Eureka Docker Image. We could then write an integration test that does the registration, heartbeat, registration and deregister.

**Comment by jquatier** [comment]
Yeah I wonder what that would look like. Do we assume they already have Docker and at least the default docker machine set up? Seems like we need something at least. I did add a wiki page for running Eureka server, for now.

**Comment by daveedgarcia** [comment]
Yeah I think it would be reasonable to have a gulp task that a task that downloads the image and starts it up. We could just update the README to get Docker setup and installed before using.

**Comment by kesne** [comment]
We can automate the docker setup in the travis build script: http://docs.travis-ci.com/user/docker/

**Comment by jquatier** [comment]
We can do this now that I figured out what the problem was. We should run these tests after coveralls so that the coverage numbers only reflect the actual unit tests.

Successful startup and cURL request:
https://travis-ci.org/jquatier/eureka-js-client/jobs/106119219

**Comment by kesne** [comment]
Awesome!!!

**Comment by jquatier** [comment]
Completed last week.
