### ISSUE TITLE
Cache inconsistency

### ISSUE THREAD

**Issue by jquatier** [jquatier/eureka-js-client#19]
Currently if there's only 1 instance for an application the entry in the cache is just an object representing that instance. If there's more than one instance (the likely scenario), the cache entry is an array of instances. We should probably transform those single instance application entries into an 1 item array for API consistency.

**Comment by daveedgarcia** [comment]
Actually working on this right now. Wrapping up the tests.

**Comment by jquatier** [comment]
I thought you might be :+1:
