### ISSUE TITLE
eureka REST endpoint is not generally correct

### ISSUE THREAD

**Issue by maksimlikharev** [jquatier/eureka-js-client#26]
return 'http://' + this.config.eureka.host + ':' + this.config.eureka.port + '/eureka/v2/apps/';

in suffix: '/eureka/v2/apps/', this is not generally how that done, prefix 'eureka' for the path, depends on deployment or might be missing at all, so this has to be configured.

**Comment by jquatier** [comment]
@maksimlikharev This should now be available in version 1.6.0 of this module. Just upgrade your dependency version and you should be good to go. Just set eureka.servicePath in your configuration.
