### ISSUE TITLE
Silent Failure

### ISSUE THREAD

**Issue by majgis** [jquatier/eureka-js-client#29]
I'm following your example in the readme and I can't get it to work.  It also silently fails.  How do I go about finding where it is failing?

**Comment by jquatier** [comment]
@majgis Could you try turning request debugging on? 
try running: `NODE_DEBUG=request node example.js`
Make sure the URLs it's calling are what you expect and that you can hit them in your browser. 

Also (I'm going to update the example with this), but you need to catch the error that comes back from start:
client.start(function(error){
  console.log(error);
});

I'll update the readme with both of these pieces of info. Let me know what you find out.

**Comment by majgis** [comment]
Both of those pieces of information were helpful, thank you for adding them to the readme.  I see the issue now.

**Comment by jquatier** [comment]
No problem! Glad you figured it out. :+1:
