### ISSUE TITLE
AWS Metadata required when datacenter == Amazon

### ISSUE THREAD

**Issue by jquatier** [jquatier/eureka-js-client#32]
Currently, we let users that implement this module define all the required metadata that they want to register with Eureka. This works fine if datacenter is set to anything other than `Amazon`, like if you were using `MyOwn`, for example. If you do set dataCenterInfo.name to `Amazon`, the Eureka server actually requires that you post a bunch of AWS metadata to it. See [the XSD](https://github.com/Netflix/eureka/wiki/Eureka-REST-operations). 

While we could just assume users will implement the code to go and fetch all the required metadata, I think it would be better to build that into the client and make it configurable. In any case it'll match what the Java client does, and users can turn it off if they would prefer to handle things in their own code.

**Comment by kesne** [comment]
Good catch, definitely should be in the module.

**Comment by kesne** [comment]
FWIW this _might_ be considered a breaking change, because if you implemented the module previously, none of the metadata would be sent by default.
