### ISSUE TITLE
Make config YAML location configurable

### ISSUE THREAD

**Issue by jquatier** [jquatier/eureka-js-client#34]
There are some people in this world that want to be able to put their eureka YAML configurations in a different directory than the project root. This should be fairly easy to add as a configurable value, still defaulting to the current work directory.

**Comment by kesne** [comment]
Maybe a `cwd` option in the constructor?

**Comment by jquatier** [comment]
:+1:

**Comment by kesne** [comment]
Working on this now.

**Comment by kesne** [comment]
Okay this should be good. We can close this when you release.
