### ISSUE TITLE
AWS metadata submitted to the Eureka server contains nulls for public-ipv4 and public-hostname when running the client with useLocalMetadata=true

### ISSUE THREAD

**Issue by tbfangel** [jquatier/eureka-js-client#56]
In continuation of #51: The AWS metadata submitted to the Eureka server when registering will alsways contain all the fields defined in AwsMetadata. When running the service in the private, values for `public-ipv4` and `public-hostname` will be null. This causes Eureka to choke when requesting the instance resource on /eureka/apps. 

This could be considered a bug in the Eureka server, but the client should not submit the null values in the first place. The solution is to filter nulls out of the AWS metadata before merging it into the config. 

I'll make a fix for this and submit a pull request.

**Comment by jquatier** [comment]
Available in v2.5.2. Thanks @tbfangel!
