### ISSUE TITLE
Use winston logging library

### ISSUE THREAD

**Issue by noseglid** [jquatier/eureka-js-client#58]
First off, thanks for building this client! It makes it easy for us to test out other technologies than Java without replacing our whole stack in one bang!

I think you should use a common logging library rather than a custom implementation. I'd vote for [winston](https://github.com/winstonjs/winston) which I've had good experiences with in the past. It would also allow me to redirect all logging from this library to e.g. a file, a database or wherever I want logs to end up.

**Comment by noseglid** [comment]
After looking through the code, I noticed that it's perfectly compatible to pass the `winston` logger as a configuration when creating the Eureka client.

**Comment by jquatier** [comment]
@noseglid Glad you found the module useful!
