### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by kesne** [jquatier/eureka-js-client#6]
We probably should figure out how we're going to handle logging. Our console logs aren't going to cut it in production.

What I propose is that we write a really small logging API that by default just wraps console. It provides all of the same log levels that console does (error, warn, info, log). You can set the log level via the config to hide logging and keep things quiet in prod.

As a bonus, we could offer a mechanism for overwriting the logger with your own (such as bunyan), so if you want formatted logs or anything special you can just drop it in.

**Comment by kesne** [comment]
Might make sense for #7 to resolve and use the provided options object to pass in a logger.

**Comment by micahr** [comment]
I'd suggest taking a logger as a configuration option, then defaulting to Bunyan.

**Comment by kesne** [comment]
Is defaulting to bunyan desired in this case though? I would make an argument that defaulting to just console is a little more sensible.

**Comment by jquatier** [comment]
Since we really only have 2 log statements and aren't using multiple log levels or anything Bunyan feels like overkill, at least at the moment. I guess I could go either way. Offering the mechanism to use Bunyan would be great though if it's not the default.

**Comment by kesne** [comment]
So I'm almost through implementing this and here's the route I've taken:

I created a Logger class with an API closely matching that of Bunyan. It's missing a couple log levels and just calls to console, but that's all you really need out of the box. In the constructor, you can pass the logger via the `logger` parameter on the configuration object. As a bonus, because the API is compatible with Bunyan, you can pass any bunyan instance without issue.

**Comment by kesne** [comment]
Fixed by #13.
