### ISSUE TITLE
Config should merge everything

### ISSUE THREAD

**Issue by kesne** [jquatier/eureka-js-client#7]
Instead of forcing users to either config via the files or with the passed in options, we should probably allow overrides at every level. I think it makes sense that config files are lower specificity than code, so I think the order of loading configuration could be as follows:

1. Load the `eureka-client.yml` config. (this is the base config)
2. Merge the `eureka-client-${env}.yml` config into the base config.
3. Merge the config object passed to the client constructor into the base config.

**Comment by kesne** [comment]
Unless anyone has an issue with this I'll probably implement it as described.

**Comment by micahr** [comment]
`Object.assign` is a great way to merge the configurations together, using a priority of base -> env -> passed in config.

**Comment by kesne** [comment]
Object.assign doesn't do deep merging though, which I thought was kind of essential in this case?

**Comment by jquatier** [comment]
Yeah, in most cases all the settings will be the same for different environments and you really just need to change 1 value (like the eureka host in your `-test.yml` config, for example). The other values should inherit from your base configuration.
