### ISSUE TITLE
Add basic round robin load balancing

### ISSUE THREAD

**Issue by caccialdo** [jquatier/eureka-js-client#75]
The java client for Eureka (aka Prana) seems to implement a "basic" load balancing strategy (round robin) according to [this article](http://southworks.com/blog/2015/09/28/netflix-oss-common-runtime-services-libraries/).

Is there any plan to add it to this library?

**Comment by daveedgarcia** [comment]
I would take a look at the [Prana Wiki](https://github.com/Netflix/Prana/wiki). Prana is an application that sits along side your non JVM based projects and provides functionality like load balancing and service discovery. Load balancing functionality in the Netflix OSS ecosystem is provided by a library called Ribbon while Eureka is meant for service discovery. I'm not sure adding load balancing would make sense in the Eureka JS client. A JS library similar to [Ribbon](https://github.com/Netflix/ribbon) would probably be the right place for this functionality.

**Comment by caccialdo** [comment]
No worries. Let's close this one then

**Comment by jquatier** [comment]
Agreed. The blog post you linked to is a little bit misleading because it says the Eureka client has a built-in load balancer, which is not correct. Anyway, keep us posted if you find a good Ribbon-like load balancer. Thanks!

**Comment by caccialdo** [comment]
👍

**Comment by NetoDevel** [comment]
I think it's interesting to put round robin load balancing, why when you communicate with another service through
`const instances = client.getInstancesByAppId ('YOURSERVICE');`
you will overload a single instance with many request.

@jquatier  the eureka has the ribbon inlaid.
So when you setup:
`ribbon.eureka.enabled = false`
the client `const instances = client.getInstancesByAppId ('YOURSERVICE');` will return you a single result, even if you have several instancies of this microservice.
If configured with:
`ribbon.eureka.enabled = true`
the client will return several results according to number of instances , being able to do the load balancer algorithm.

**Comment by jquatier** [comment]
I haven't seen a direct replacement for Ribbon in JS. Typically users of this module implement their own http client with load balancing built-in along with other things like retries and circuit breaking. In any case, if one was developed it could easily pull in this module for it's discovery client, similar to how Ribbon and the Java Eureka client work together. Ideally, the load balancer should allow you to inject different strategies and instance selection utilities to allow you to use multiple methods of retrieving instances (not just Eureka).

**Comment by colin-riddell** [comment]
Newbie question on this: Does this mean that eureka-js-client won't work with other services using ribbon?

**Comment by jquatier** [comment]
It works great with all kinds of services, including those using ribbon. Ribbon and Eureka are 2 very different things. Ribbon is a software load balancer and Eureka is a service registry. They are often used together; Eureka will return a list of servers that are hosting the desired microservice, and Ribbon will balance between those servers.

This library only aims to be a eureka client for retrieving the list of servers from the registry. Once you have that list, you can use any number of methods to choose a server to make a request to (round robin, random, or other algorithms).
