### ISSUE TITLE
Add support for authentication

### ISSUE THREAD

**Issue by dflor003** [jquatier/eureka-js-client#82]
Correct me if I'm wrong, but there doesn't seem to be a way to plug in authentication mechanisms such as an `authorize` header when communicating with eureka.

Are there plans for extending the client for this?

The specific use case I'm running into auth issues with is when trying to integrate this into Pivotal's Cloud Foundry cloud services.

**Comment by fmmontas** [comment]
+1

**Comment by jquatier** [comment]
We've got an upcoming PR (Thanks @awolden!) that will add support for this in the v4 branch. The implementation in v4 is slightly different than it would be in master so I suggest this goes into v4 (with a few other new features we've been developing). Anyway, we'll add you guys to the PR so you can take a look. Thanks for the report!

**Comment by dflor003** [comment]
Awesome! Glad to hear. I was actually about to submit a PR for this myself. I'll take a look and see if I can pull that version for testing. Thanks!

**Comment by jquatier** [comment]
Should be ready to go in v4.0.0. Thanks @dflor003 for helping us with this feature! If you are interested, I'd love a short snippet in the README about integration with Cloud Foundry (similar to what we have to Spring Cloud. It might help others who stumble upon our project from Google.

**Comment by dflor003** [comment]
Sounds good. I'm actually still working through all of the issues with eureka itself, but once I have it all ironed out, I'd be happy to submit some documentation on getting it setup in Cloud Foundry (which I think uses Spring Cloud underneath the hood).

**Comment by jquatier** [comment]
Hey @dflor003 just checking if you wanted to share what you needed to do to get things running on Pivotal Cloud Foundry. It might be useful to add a snippet in our docs. Thanks again!
