### ISSUE TITLE
Enable read-only scenarios

### ISSUE THREAD

**Issue by mhamann** [jquatier/eureka-js-client#86]
There are times when you don't want to register a service / instance with Eureka, but only want to discover other registered apps (i.e. read-only).

Currently, this module requires passing in an `instance` object with certain values set; however, I think it would be desirable to pass in an option like `registerInstance: false` that then makes the `instance` object optional as part of constructing a Eureka client.

**Comment by jquatier** [comment]
I think my question would be if you still want the client to refresh the registry on interval or if you want to call `fetchRegistry(callback)` yourself. It seems like it might be useful to still be able to call `start()` and have the client keep the registry up to date, but make the `register()` call be a no-op. That way you can just call `getInstancesByAppId` etc like normal.

**Comment by mhamann** [comment]
Yes, I agree. Calling `start()` should still be a thing and the registry should fetch by default per usual, unless explicitly disabled.

**Comment by trinakria** [comment]
Hi jquatier,

any update on this? I am in the same situation as @mhamann  where I don't want to register each client ui that needs access to the registry.

**Comment by jquatier** [comment]
@trinakria PR is in flight for this.
