### ISSUE TITLE
Support for homePageUrl

### ISSUE THREAD

**Issue by danielbayerlein** [jquatier/eureka-js-client#88]
At the moment eureka-js-client supports `healthCheckUrl` and `statusPageUrl`. I miss the support for `homePageUrl`. Are you interested in a PR that support that?

Eureka REST documentation: https://github.com/Netflix/eureka/wiki/Eureka-REST-operations

**Comment by jquatier** [comment]
Thanks for the heads up! We currently POST the entire `config.instance` block on the register request. So, technically `homePageUrl` is already supported if you just add it to your config block. That being said, we do have some code around `statusPageUrl` and `healthCheckUrl` in the `addInstanceMetadata` method [here](https://github.com/jquatier/eureka-js-client/blob/master/src/EurekaClient.js#L413) that replaces the host key with the hostname from the AWS metadata, so maybe that's what you're referring to (this would only apply to AWS environments).

Would love a PR that updates that method to support `homePageUrl` and the README (just the configuration example). Thanks @danielbayerlein!

**Comment by jquatier** [comment]
Thanks @danielbayerlein! Just published v4.1.0.
