### ISSUE TITLE
`started` event should not be emitted if the Eureka connection failed to start

### ISSUE THREAD

**Issue by mhamann** [jquatier/eureka-js-client#91]
According to the docs, the client should emit the `started` event when "the eureka client is fully registered and all registries have been updated."

However, based on the code here, it seems like the `started` event is fired no matter what.
https://github.com/jquatier/eureka-js-client/blob/fb80dd6740d45ec480e497a9c7b386024357e9ff/src/EurekaClient.js#L148

So, if you have an app depending on Eureka, it will try to get data even though Eureka's connection failed.

**Comment by jquatier** [comment]
Thanks for finding this @mhamann! Fixed in v4.1.1
